# Generated by Django 2.0.7 on 2018-07-20 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saltapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='机房名称')),
                ('address', models.CharField(max_length=64, verbose_name='机房地址')),
                ('contact', models.CharField(max_length=32, verbose_name='联系人')),
                ('phone', models.CharField(max_length=32, verbose_name='联系电话')),
                ('network', models.TextField(blank=True, null=True, verbose_name='IP地址段')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('update_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '机房管理',
                'verbose_name_plural': '机房管理',
            },
        ),
        migrations.CreateModel(
            name='ISP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='运营商')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='网卡名称')),
                ('address', models.CharField(max_length=15, verbose_name='IP地址')),
                ('mac', models.CharField(max_length=17, verbose_name='Mac地址')),
            ],
            options={
                'verbose_name': '网卡管理',
                'verbose_name_plural': '网卡管理',
            },
        ),
        migrations.CreateModel(
            name='ServerAsset',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP')),
                ('status', models.IntegerField(choices=[(1, '运营中'), (2, '未上线'), (3, '故障中'), (4, '维修中'), (5, '开发机'), (6, '测试机'), (7, '下线')], default=1, verbose_name='状态')),
                ('manufacturer', models.CharField(blank=True, max_length=20, verbose_name='厂商')),
                ('productname', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('sn', models.CharField(blank=True, max_length=100, verbose_name='序列号')),
                ('cpu_model', models.CharField(blank=True, max_length=100, verbose_name='CPU型号')),
                ('cpu_nums', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='CPU线程')),
                ('memory', models.CharField(blank=True, max_length=20, verbose_name='内存')),
                ('disk', models.TextField(blank=True, verbose_name='硬盘')),
                ('os', models.CharField(blank=True, max_length=200, verbose_name='操作系统')),
                ('virtual', models.CharField(blank=True, max_length=20, verbose_name='虚拟化')),
                ('kernel', models.CharField(blank=True, max_length=200, verbose_name='内核')),
                ('shell', models.CharField(blank=True, max_length=10, verbose_name='Shell')),
                ('selinux', models.CharField(blank=True, max_length=50, verbose_name='Selinux')),
                ('locale', models.CharField(blank=True, max_length=200, verbose_name='编码')),
                ('saltversion', models.CharField(blank=True, max_length=10, verbose_name='Salt版本')),
                ('minion_status', models.IntegerField(choices=[(1, '正常'), (2, '未安装')], default=2, verbose_name='Minion状态')),
                ('update_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('dev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dev', to=settings.AUTH_USER_MODEL, verbose_name='开发负责人')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.IDC', verbose_name='机房')),
                ('ops', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops', to=settings.AUTH_USER_MODEL, verbose_name='运维负责人')),
                ('salt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saltapi.Salt', verbose_name='Salt-Master')),
            ],
            options={
                'verbose_name': '主机资产信息',
                'verbose_name_plural': '主机资产信息管理',
            },
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.ServerAsset', verbose_name='主机'),
        ),
        migrations.AddField(
            model_name='idc',
            name='isp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.ISP', verbose_name='运营商名称'),
        ),
        migrations.AlterUniqueTogether(
            name='networkinterface',
            unique_together={('name', 'server')},
        ),
    ]
