# Generated by Django 2.0.7 on 2018-07-20 10:52

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='用户名')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='邮箱')),
                ('mobile', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+()-]+$', 'Enter a valid mobile number.', 'invalid')], verbose_name='手机')),
                ('fullname', models.CharField(max_length=64, null=True, verbose_name='中文姓名')),
                ('is_active', models.BooleanField(default=False, verbose_name='状态')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='超级管理员')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近登录时间')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
