# Generated by Django 2.0.7 on 2018-07-20 10:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minions',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('minion', models.CharField(max_length=50, unique=True, verbose_name='客户端')),
                ('status', models.IntegerField(choices=[(0, 'Accepted'), (1, 'Unaccepted'), (2, 'Rejected'), (3, 'Denied'), (4, 'Unknown')], default=4, verbose_name='Key状态')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Salt客户端',
                'verbose_name_plural': 'Salt客户端列表',
            },
        ),
        migrations.CreateModel(
            name='Salt',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='SaltAPI名称')),
                ('host', models.URLField(max_length=64, verbose_name='SaltAPI地址')),
                ('username', models.CharField(default='admin', max_length=64, verbose_name='SaltAPI用户名')),
                ('password', models.CharField(max_length=64, verbose_name='SaltAPI密码')),
                ('status', models.IntegerField(choices=[(0, '不在线'), (1, '在线')], verbose_name='状态')),
                ('comment', models.CharField(max_length=64, verbose_name='注释')),
                ('update_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'SaltAPI信息',
                'verbose_name_plural': 'SaltAPI信息',
            },
        ),
        migrations.AddField(
            model_name='minions',
            name='saltserver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saltapi.Salt', verbose_name='所属Salt服务器'),
        ),
    ]
